### ISSUE TITLE
Permissions are not set in the DEB when running jdeb on Centos

### ISSUE THREAD

**Issue by RockyMM** [tcurdt/jdeb#134]
Hi!

I have had not any issue when running jdeb on Windows. All <mapper> sections are applied correctly and all files in the archive have proper owner. 

But, my integration server is on CentOS. DEBs produced on this integration server have all ownerships set to "root.root". This forced me to write chowns in postinst, which I should not have to do since mapper should be picked up by jdeb.

**Comment by RockyMM** [comment]
Hi all.

I am now packing my project with jdeb 1.4 and I am not experiencing this behaviour. If it happens again, I'll create a quick test project.

**Comment by Jan-Marcek** [comment]
Hm, I had an experience with a similar problem (maybe same). The problem was when a owner of file doesn't match user. 

Lets have a section:
```                                     
 <data>
   <src>${basedir}/src/deb/file</src>
   <type>file</type>
   <mapper>
      <type>perm</type>
      <prefix>/var/lib/test<prefix>
      <user>test</user>
      <group>test</group>
    </mapper>
</data>
```
The owner is set to test:test (chown test:test ), but if the user test doesn't exists in OS then the owner of file will be root:root. This is how OS works, you can't set the owner of file to user who doesn't exist.
I think you deal with same situation.

**Comment by RockyMM** [comment]
Hm, it might be just that. I don't remember exactly what I did, but rereading my issue description it seems to me that my integration server was creating archives with only root user, while my Windows workstation was creating archives with proper user settings. The user in question is "tomcat7". My app should have been installed after Tomcat; I really cannot recall had I switched a step or two while testing the installation of the app.
