### ISSUE TITLE
*.changes file is not copied during install/release:perform into maven repository

### ISSUE THREAD

**Issue by vnashkev** [tcurdt/jdeb#232]
Hi, thanks a lot for the beautiful plugin.

I just built a simple dummy deb-package and noticed that generated *.changes file was not copied neither to local .m2 repo nor to remote (release:prepare).
I plan to use dput to send built package to apt-repo but it requires *.changes file.
Any idea?

Thank you in advance, Vitali

**Comment by tcurdt** [comment]
The changes files should go into the apt-repo - not the maven repo.

**Comment by vnashkev** [comment]
please consider the following scenario:

new release is built. Sometime later i decide to deploy package to apt-repo.
I cannot do it because *.changes file is lost (was not deployed to maven repo).
I would suggest to deploy *.changes file as well as *.deb. At least i do not see any reason against that.
Am i completely wrong?

Thank you in advance, Vitali

**Comment by ebourg** [comment]
The .deb package shouldn't go into the Maven repository IMHO, neither the changes files. These files are meant to be served by an APT repository.

**Comment by tmortagne** [comment]
Actually its very nice to have the .deb stored in the Maven repository when you release, makes very easy to automate a Debian repository.

And anyway since that's what the project produces it's expected for me to have it deployed in the Maven repository which is the reference. If it's not then you have a good chance to simply loose it after the release because you did not extracted it right way from the target/ folder to put it somewhere.

**Comment by tcurdt** [comment]
Should we confirm this with the repo guys maybe?

**Comment by ebourg** [comment]
Maybe it's possible to use the build-helper-maven-plugin to attach the .changes file and get it deployed to the Maven repository?

**Comment by tmortagne** [comment]
On jdeb side attaching other files is would be just about MavenProject#addAttachedArtifact I think.
