### ISSUE TITLE
Customizing deb file name

### ISSUE THREAD

**Issue by alvise72** [tcurdt/jdeb#242]
Hello,
concerning the <deb>...</deb> section, where can I find the list of supported variables ${...} ?
I'd need to add something like _${architecture} just after the -${version}, getting its value from the control file.
thanks.

   Alvise

**Comment by rednoah** [comment]
Since `control` files are (almost) the same as `.property` files you can probably import them as if they were:
```xml
<property file="build.properties"/>
```
But you shouldn't do that!


I recommend that you generate the `control` file from some template via ant copy/replace like in all the examples:
https://github.com/tcurdt/jdeb/blob/master/src/examples/ant/build.xml#L33
https://github.com/tcurdt/jdeb/blob/master/src/examples/ant/src/deb/control/control#L2

**Comment by tcurdt** [comment]
I guess that's answered. Otherwise please re-open.
