### ISSUE TITLE
traverse runtime dependencies

### ISSUE THREAD

**Issue by fabien-degroote-dev** [tcurdt/jdeb#334]
Hi,

io-solit (https://github.com/io-solit/deb-maven-plugin) is offering the possibility to retrieve from maven the runtime dependencies and add them somehow into the generated deb.
Is jdeb offering the same functionality?
If yes, could you please provide an example (couldn't find it anywhere)?
If not, do you think it would be useful to add such mechanism in jdeb?
Last, I can offer my service to implement it

**Comment by tcurdt** [comment]
While this could be added in a not so great way, I believe this is out of the scope of jdeb. To explain: I don't agree with the debian way to ship java libraries as debs. And specifying library dependencies the debian way is close to impossible to automate.

Just adding them the deps to the deb has no real benefit (as you cannot update them outside of the release cycle anyway). There is just no upside of doing it this way.

There are plenty of ways to bundle dependencies which is (IMHO) a much better way to approach this. I'd suggest to instead encapsulate the deps.

I'd just use the maven shade plugin to create an uberjar and be done with it.
If desired this even allows for stripping unused code to reduce the size of the final jar.
A much much simpler way - and it works today.

**Comment by tcurdt** [comment]
Instead of delivering multiple jars you would only deliver a single jar. Think of it as a your 'zip'. To give an example:

This projects uses [all these dependencies](https://github.com/tcurdt/jdependency/blob/master/pom.xml#L56). But [using the shade plugin](https://github.com/tcurdt/jdependency/blob/master/pom.xml#L224) the final build artifact will be a single jar.

This has a couple of benefits. One of them is you can just run that single jar without any startup scripts. It also means that `jdeb` can just package the one jar. Done.

As an example maybe just clone and try to build https://github.com/tcurdt/jdependency to see this in action. That should hopefully clear things up for you.

**Comment by tcurdt** [comment]
I hope the answer was helpful. I am closing this for now.
